### ISSUE TITLE
Documentation for AwsS3 dependency 

### ISSUE THREAD

**Issue by phillipsnick** [KnpLabs/KnpGaufretteBundle#109]
Might seem fairly obvious, but after 10 hours my brain is struggling with simple tasks! Also might help someone else out :)

Think it would be good to add something for AwsS3 in the README, along the lines of (much like Amazon S3):
## AwsS3

Adapter for Amazon S3 SDK v2.

This adapter requires the use of aws/aws-sdk-php which can be installed by adding the following line to your composer.json:

```
    "require": {
        ...
        "aws/aws-sdk-php": "~2.7"
    },
```

**Comment by pwintermantel** [comment]
+1 especially since the amazon_s3 adapter also lists the dependency, like you said...

**Comment by grizzlylab** [comment]
+1

**Comment by AlexandreHagen** [comment]
+1

**Comment by acanimal** [comment]
+1

**Comment by james-bw** [comment]
+1
