### ISSUE TITLE
Please tag a new stable version of the bundle

### ISSUE THREAD

**Issue by stof** [KnpLabs/KnpGaufretteBundle#118]
The latest stable release is very old and many changes have been done since then. Anyone using the default setting of Composer (min-stability=stable) will never benefit from unreleased changes.

**Comment by kwn** [comment]
+1

**Comment by vvondra** [comment]
+1

**Comment by numerogeek** [comment]
+1

**Comment by stof** [comment]
@docteurklein you forgot this repo in your releasing mood yesterday

**Comment by docteurklein** [comment]
indeed. Thanks for pointing this out.

**Comment by stof** [comment]
@docteurklein ping. Please make a 0.2 release of the bundle (or 1.0 if you want)

**Comment by docteurklein** [comment]
released https://github.com/KnpLabs/KnpGaufretteBundle/releases/tag/0.2.0
