### ISSUE TITLE
SFTP Adapeter: Permission denied on remote host but no error was thrown

### ISSUE THREAD

**Issue by skonsoft** [KnpLabs/KnpGaufretteBundle#122]
Hello,

Sftp Works well when the user has the right permissions to write in the remote dir, but when it has not that rights, sftp don't throw any error and print that everything is ok.

the problem is in the method:

```php
    protected function ensureDirectoryExists($directory, $create = false)
    {
        $url = $this->sftp->getUrl($directory);

        $resource = @opendir($url); 

// Here is the problem.
        if (false === $resource && (!$create || !$this->createDirectory($directory))) {
            throw new \RuntimeException(sprintf('The directory \'%s\' does not exist and could not be created.', $directory));
        }
        
        // make sure we don't leak the resource
        if (is_resource($resource)) {
            closedir($resource);
        }
    }
```

the line:
`  if (false === $resource && (!$create || !$this->createDirectory($directory))) {`

should be changed. It contains a resource regardless of the real result whish should be false in case  of no permissions.

To be sure that really directoty is readable, i added this condtion:

```php 
if(false === @readdir($resource)){
            throw new \RuntimeException(sprintf('The directory \'%s\' is not radable.', $directory));
  }
```
just before : // make sure we don't leak the resource

and it works !

Please can you make a patch for this line ?

Thank you

**Comment by akovalyov** [comment]
@skonsoft thank you for the report!
I am really sorry that we came a little bit too much later then you expected. 
Is it still the case for you? Could you provide a PR in https://github.com/KnpLabs/Gaufrette ? 
Just tell me, if you have no time for that - I will create a PR for that so that you can test and confirm if it works for you.

Thanks in advance.

**Comment by NiR-** [comment]
Hello @skonsoft, we will drop ssh extension support soon. I recommend you to use phpseclib sftp adapter.
