### ISSUE TITLE
Better explanation of Cache features

### ISSUE THREAD

**Issue by JHGitty** [KnpLabs/KnpGaufretteBundle#126]
I like to use the cache features of Gaufrette.

Currently I know Doctrine Cache, SncRedis, memcached, ..

How could I use SncRedis or Doctrine Cache? Is it possible or not?
Should I write any own cache adapter for Gaufrette to use it?

I don't know if these cache adapters are following a PSR or any other generic interfaces to use together. Is it possible or not? If yes: How? If no: How could I write my own cache adapter?

It would be great to update the documentation about this.

**Comment by JHGitty** [comment]
ping @akovalyov Could you please add the "Docs" label?

**Comment by akovalyov** [comment]
@JHGitty putting the label. However, I am not sure about the ETA for it, but it is definitely something in the todo.

**Comment by akovalyov** [comment]
@JHGitty returning back to you with some kind of answers:
1. https://knplabs.github.io/Gaufrette/caching.html describes the basic idea of cache adapter. To be precise - you can use any adapter available in Gaufrette as source and dest. Moreover, after https://github.com/KnpLabs/Gaufrette/pull/390 you can use any adapter implementation available for Gaufrette and Flysystem.
2. https://github.com/KnpLabs/Gaufrette/blob/master/doc/implementing-new-adapter.md (should be on the main docs site soon) is about new adapter creation.

Current implementation doesn't support PSR-6 and it is not planned to add one in the nearest roadmap. 

Please, let me know if you have any questions (or I have forgotten to answer any).
