### ISSUE TITLE
SFTP Folder delete does not delete Folder

### ISSUE THREAD

**Issue by yunai39** [KnpLabs/KnpGaufretteBundle#132]
Good Morning,

I'm currently using GaufretteBundle with an SFTP acces using the php-ssh bundle from Herzult

Everything work find except when I want to remove a folder. 
The folder is empty and the user which is tring to delete it, is the owner and has the right to do it.
I was wondering if I anyone had ever encountered this issus

Thanks

**Comment by yunai39** [comment]
Actually, I think I found my answers, 
in the Sftp Adapter, there is nothing to check if the key is a file or a folder
I changed the delete function of the adapter to this:

    public function delete($key)
    {
        $this->initialize();

        if ($this->isDirectory($key)) {
            return rmdir($this->sftp->getUrl($this->computePath($key)));
        }
        return unlink($this->sftp->getUrl($this->computePath($key)));
    }

And now everything seem to work fine

**Comment by akovalyov** [comment]
@yunai39 could you open a PR in https://github.com/KnpLabs/Gaufrette/ for it and ping me there?

**Comment by NiR-** [comment]
@yunai39 Thank you for this bug report but unfortunately we will drop ssh extension support soon. I can only recommend you to use the Phpseclib sftp adapter.
