### ISSUE TITLE
Status of this bundle

### ISSUE THREAD

**Issue by JHGitty** [KnpLabs/KnpGaufretteBundle#133]
Why is this bundle not maintained? There are some great Pull Requests and the Symfony 3 update is not tagged.

**Comment by mappedinn** [comment]
:+1:

**Comment by claretcrab** [comment]
+1

**Comment by JHGitty** [comment]
I think this bundle is important for the Symfony community because it implements file abstraction layers. We need anybody who maintain this bundle.

**Comment by akovalyov** [comment]
@JHGitty hey.
Indeed, recently there was a lack of activity on this project. We are trying to change that. As for Symfony3 support, it is tagged as [0.3.0](https://github.com/KnpLabs/KnpGaufretteBundle/releases/tag/0.3.0). To help us in prioritizing things, just mention me or/and @NiR- on the PRs which are needed/nice to have.
Thank you.

**Comment by JHGitty** [comment]
:+1: Great. Thank you!
