### ISSUE TITLE
Stable versions

### ISSUE THREAD

**Issue by mmoreram** [KnpLabs/KnpGaufretteBundle#134]
During the last hours in my project we have experimented an strange behavior.
We've had since now `^0.1.7`, and as long as this package have tagged `v0.3.0` to allow compatibility with Symfony, we were happy because, supposedly, `^0.1.7` should allow `v0.3.0` to be installed.

Well, is not that way.
This is part of the composer documentation - https://getcomposer.org/doc/articles/versions.md#caret

```
For pre-1.0 versions it also acts with safety in mind and treats ^0.3 as >=0.3.0 <0.4.0.
```

So, would be nice if these projects (both KNPGaufretteBundle and Gaufrette) are released as stables. Then we will be able to work with semver in our projects.

What do you think?

**Comment by NiR-** [comment]
Hey @mmoreram, we are currently working on it. We will try to merge PRs, close issues in the next days, and finally we will try to release a stable version.
