### ISSUE TITLE
Support for Azure multi-container mode

### ISSUE THREAD

**Issue by dkarlovi** [KnpLabs/KnpGaufretteBundle#157]
Since we've added MC mode, I'm just now trying to set it up in one of my apps, but cannot as [`container` is not allowed to be empty](https://github.com/KnpLabs/KnpGaufretteBundle/blob/master/DependencyInjection/Factory/AzureBlobStorageAdapterFactory.php#L42). :(

/cc @NiR- this is a good reason to go for a mono-repo, my original PR should have covered this too.

**Comment by NiR-** [comment]
Indeed, I created a new project and added a note about multi container mode yesterday. It needs to be fix.

For the mono-repo, I'm not sure if that's a good idea or not: for instance laravel users would have `symony/framework-bundle` installed for nothing, inflating their dependency hell.

**Comment by dkarlovi** [comment]
No, I meant the mono **dev** repo, same way Symfony or Enqueue do: one repo for all development, split into smaller read-only repos which are registered on Packagist. Everything stays the same for end users, but you get to sync changes across multiple packages (as needed here).

**Comment by NiR-** [comment]
Indeed it would be better. IIRC, we talked about this solution some weeks ago. It's not our top priority right now but we'll switch to it in some time.

#158 should solve your issue, could you confirm?

**Comment by dkarlovi** [comment]
It does, thanks! \o/

**Comment by dkarlovi** [comment]
@NiR-  semi-related, but how do I override the adapter service? For example, I'd like to [inject default container options](https://github.com/KnpLabs/Gaufrette/blob/master/src/Gaufrette/Adapter/AzureBlobStorage.php#L92) (to be able to make the container public read-only by default, for example). Don't see a way to do this currently.

**Comment by NiR-** [comment]
Mmh good question. You can decorate/override the factory service, or you can use a CompilerPass to modify the service declaration for the adapter.

**Comment by dkarlovi** [comment]
Might want to make that a bit more user friendly. :) Maybe allowing users to tag their custom adapter?

**Comment by dkarlovi** [comment]
Hm, I can see you're already doing some of that with `gaufrette.adapter`. If I tag and alias my service as `knp_gaufrette.adapter.azure_blob_storage`, might that work? Will try.

**Comment by dkarlovi** [comment]
It doesn't as you're creating an a service for each adapter instance, d'oh. :) OK, compiler pass it is, thanks!

**Comment by NiR-** [comment]
Indeed we need a more user-friendly way of setting CreateContainerOptions. Do you think a `create_container_options` key would be good enough?

**Comment by dkarlovi** [comment]
It would accept a service ID, same as factory? Sure, that works.

But I thinks it's more important to consider the underlying problem: how to allow users to have their own adapter services, that way you wouldn't need to have an explicit config for each dependency, you can have a basic set (as is now) and delegate any more advanced requirements to the DIC.
