### ISSUE TITLE
Knp Gaufrette Bundle Google storage bucket does not exist

### ISSUE THREAD

**Issue by shubaivan** [KnpLabs/KnpGaufretteBundle#167]
I use `knplabs/knp-gaufrette-bundle` and google cloud storage. 

    knp_gaufrette:
    stream_wrapper: ~
    adapters:
        ebook_images:
            google_cloud_storage:
                service_id: 'app.google_cloud_storage.service'
                bucket_name: '%google_api.bucket%'
                options:
                    directory: 'ebook'
    filesystems:
        ebook:
            adapter: ebook_images
    
and create bucket in google storage but have error 

 `The configured bucket "images" does not exist.`

What I'am doing wrong ? 
[![enter image description here][1]][1]
[![enter image description here][2]][2]

  [1]: https://i.stack.imgur.com/WyG0R.jpg
  [2]: https://i.stack.imgur.com/zt4Ew.jpg

**Comment by 7thcubic** [comment]
seems to be api permission issue on your google service account.
https://cloud.google.com/storage/docs/access-control/

**Comment by nicolasmure** [comment]
Hello @shubaivan , any updates on this ?

**Comment by shubaivan** [comment]
atm wrk, I open all permission in google account
