### ISSUE TITLE
When will the new 0.5 version will be released?

### ISSUE THREAD

**Issue by Aerendir** [KnpLabs/KnpGaufretteBundle#174]
I receive a deprecation error from this bundle as it access directly the service `knp_gaufrette.filesystem_map`.

I've seen the issue is already fixed so, when the new `0.5` version will be released? Because without this fix it is not possible to upgrade to the new Symfony 4 version...

**Comment by NiR-** [comment]
Soon :) We need to merge #173 first, and then we'll release a new version of this bundle ;)

**Comment by thomasglachant** [comment]
#173 is now merged, any idea about a release date ?

**Comment by NiR-** [comment]
We finally released v0.5.0 just now. Enjoy!
