### ISSUE TITLE
No stable release

### ISSUE THREAD

**Issue by Nek-** [KnpLabs/KnpGaufretteBundle#180]
Hello,

First thanks for this package. Gaufrette is one of the most used library for file management in PHP. This bundle is a great plugin for Symfony.

I assume you use semver to manage versions of this project. This bundle is in version 0.5.x currently. This is an issue because it means this project is not stable (on a semver POV), for many people it's a no-go for production.

**Does it mean that you don't recommend its usage?**

Otherwise, why not releasing a stable release? What's missing so people can help?

Let's make a list 🙂.

**Comment by PedroTroller** [comment]
Hello @Nek-.

The gaufrette version 1.0 is on the way but the current version is already stable.

You can take a look to the project board (https://github.com/KnpLabs/Gaufrette/projects/1) if you want to help.

Enjoy :wink:.

PS: semver just recommands to use 1.0 for first stable version, this is not because the major version is 0 that the library is not stable (cf: imagine, phpstan and a lot of other examples I don't have time to list).

**Comment by Nek-** [comment]
I think you should let this issue open so people are aware of your choice of being under 1.0.0 while the project is "officially" stable. (this may be a rename of the issue like "note about stability")

Btw there's no trace of semver in imagine. [The bundle](https://github.com/liip/LiipImagineBundle) otherwise respect it.

**Comment by Nek-** [comment]
[Semver](https://semver.org/#spec-item-4) specify clearly:

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

That's why I suggest keeping this issue open for information.

**Comment by Pierstoval** [comment]
> That's why I suggest keeping this issue open for information.

Or better: release a v1.0.0 just for the sake of semver. After all, what's the problem if the project is stable?

**Comment by Nek-** [comment]
Versioning follows Gaufrette. It's not semver actually. The problem is that it looks like it is :). (and according to @PedroTroller _it is_ semver)

But I think Gaufrette may also get its 1.0.0 version :). (after all, it's stable too, right?)
