### ISSUE TITLE
Adapter or Filesystem : which one should I use ?

### ISSUE THREAD

**Issue by FradiFrad** [KnpLabs/KnpGaufretteBundle#186]
Hi,

I'm testing GaufretteBundle on a Sf 3.4.4 project. It's working great but I have a question about good practices : do I have to call the adapter to read, write, etc. files ? Or do I have to use filesystem instead ? I've seen that both are possible.

```
 $adapter = $this->filesystem->getAdapter();
 $adapter->write($filename, file_get_contents($file->getPathname()));
```
or directly :
```
$this->filesystem->write($filename, file_get_contents($file->getPathname()));
```

Many thanks.

**Comment by nicolasmure** [comment]
Hello :)

Even if both solutions are working, I recommend that you use the filesystem approach as it is adapter agnostic. Your gaufrette configuration should expose filesystems that you should inject as services. Your classes using these services won't change if you change your configuration (ie if you change which adapter to use for this filesystem).

The filesystem is the one with the highest abstraction level, so this is the one that you should use :)

**Comment by FradiFrad** [comment]
Many thanks for your quick answer !
