### ISSUE TITLE
using ContainerAwareCommand deprecated in symfony 4.2

### ISSUE THREAD

**Issue by timgregg** [KnpLabs/KnpGaufretteBundle#208]
After upgrading to symfony 4.2 getting this deprecation error

`  1x: The "Knp\Bundle\GaufretteBundle\Command\FilesystemKeysCommand" class extends "Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand" that is deprecated since Symfony 4.2, use {@see Command} instead.`

can be fixed by using  "Symfony\Component\Console\Command\Command" instead

**Comment by timgregg** [comment]
#209

**Comment by florianajir** [comment]
+1

**Comment by nicolasmure** [comment]
Fixed by #210 , thank you for reporting.
