### ISSUE TITLE
Add README and instructions about AmazonS3 usage

### ISSUE THREAD

**Issue by bitomule** [KnpLabs/KnpGaufretteBundle#21]
Hi, I'm trying to use Amazon S3 as filesystem using KnpGaufretteBundle but I don't understand how to do it and readme doesn't show anything about S3. Could anyone explain me what should I do? :(

Thanks!

**Comment by akovalyov** [comment]
Well, this issue is almost three years old.
So, how do you feel guys, is the docs in https://github.com/KnpLabs/KnpGaufretteBundle#amazon-s3-amazon_s3 enough for the moment? 
Should we update it?
What are you missing in the current doc?
Thanks in advance.

**Comment by mappedinn** [comment]
:+1:

**Comment by KevinArtus** [comment]
I close this issue. As mentioned by @akovalyov, a documentation is available. Please feel free to reopen it if necessary.
