### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by Icewild** [KnpLabs/KnpGaufretteBundle#216]
Hello! Could you please create new release tag with this commit https://github.com/KnpLabs/KnpGaufretteBundle/commit/0ca1609d85b4a3ec4d698111bf04d21888866a16?

**Comment by nicolasmure** [comment]
Hello @Icewild ,
[`v0.6.0`](https://github.com/KnpLabs/KnpGaufretteBundle/releases/tag/v0.6.0) is out since yesterday ind include these changes ;)

**Comment by Icewild** [comment]
Thank you, @nicolasmure !
