### ISSUE TITLE
Compatibility with Symfony 3.4

### ISSUE THREAD

**Issue by hhamon** [KnpLabs/KnpGaufretteBundle#220]
Hello !

Is there any reasons why version `0.6` requires Symfony 4 and drops support for Symfony 3.4?

Thanks.

**Comment by nicolasmure** [comment]
Hello,

Indeed there was a mistake on deps upgrade, SF 3.4 is LTS so the bundle should be usable with it.

Thank you for reporting, the issue will be fixed by #221 .

**Comment by hhamon** [comment]
Thanks ;)
