### ISSUE TITLE
Remove FrameworkBundle dependency

### ISSUE THREAD

**Issue by garak** [KnpLabs/KnpGaufretteBundle#232]
Since commit 51d40c1c3aa1a2cc76be0dd6c7cfab9ee53b5e09, FrameworkBundle is not used by KnpGaufretteBundle.
It should be removed from dependencies.

**Comment by nm2107** [comment]
Thanks for pointing it out :+1: . This should be addressed when we'll drop support for SF3.4.

**Comment by GromNaN** [comment]
Hello, Symfony 3.4 is not maintained anymore. The bundle could move to Symfony 4.4+
