### ISSUE TITLE
Support for knplabs/gaufrette 0.10.0

### ISSUE THREAD

**Issue by lstrojny** [KnpLabs/KnpGaufretteBundle#241]
0.7.1 requires `knplabs/gaufrette (^0.8.2|^0.9)`, would be nice to support 0.10.0 as well.

**Comment by tobias-93** [comment]
The changes to support version 0.10.0 have been done on master, the only thing necessary is a new release. @Nyholm would you be able to make a new release in the near future?

**Comment by sylvain-duval** [comment]
Hello, we are actually in the process to support symfony 5 in our project.
One bundle we are using require knplabs/gaufrette 0.10.0 therefore it conflicts with KnpGaufretteBundle locked to 0.9.
Is there a new release coming to support 0.10.0 ?
Thank you @Nyholm
