### ISSUE TITLE
why releases are stoped ?

### ISSUE THREAD

**Issue by asuri0n** [KnpLabs/KnpGaufretteBundle#257]
Is this project still maintained? 
I can see PRs opened, but the releases are no longer progressing (0.7.1). I'm stuck to switch to Symfony 6 on my project that uses Gaufrette.

**Comment by mirandaguillaume** [comment]
I have the same issue, should we migrate to master ?

**Comment by asuri0n** [comment]
[@NiR-](https://github.com/NiR-)
[@nicolasmure](https://github.com/nicolasmure)

**Comment by Nek-** [comment]
I'm not sure the 2 you tagged are still developers or still contributing to OSS. @alexpozzi seems to have rights on this bundle.

**Comment by alexpozzi** [comment]
Hello,
I unfortunately don't have enough time to maintain this project and, therefore I can't help you much with that.
I'm using this package on a customer's project as well and, at some point, if no one will release a SF6 compatible version by then, I'm gonna try to schedule the time needed for it.
What I can do though is to review applications for potential maintainers and grant the necessary access to the repository.
@Nek- are you willing to maintain the project?

**Comment by Nek-** [comment]
Lol, the story repeating itself. I will have control over all OSS in a few years! (please notice my time is not especially more extensible than other people)

But well, I'm ok, I can try to handle the most important maintenance needs.

Merge https://github.com/KnpLabs/KnpGaufretteBundle/pull/260 and count me in.

**Comment by alexpozzi** [comment]
Of course, everyone's time is limited and my intention wasn't to try to force you to become a maintainer of this package.
You can count on me for code reviews, this is the only thing I can promise from my side.

**Comment by Nek-** [comment]
@alexpozzi then feel free to review and merge https://github.com/KnpLabs/KnpGaufretteBundle/pull/260 before promoting me on the repository :) .

**Comment by alexpozzi** [comment]
Done, thank you!

**Comment by Nek-** [comment]
@alexpozzi thanks for the merge, I still have no rights on the repository.

**Comment by alexpozzi** [comment]
I invited you to be a maintainer for this repository and I can still see the invitation in pending state.
I'm gonna try to do it again :wink:

**Comment by Nek-** [comment]
Notification in spam. It seems to be good now! thanks
