### ISSUE TITLE
Support PHP 8.1

### ISSUE THREAD

**Issue by Alg1d** [KnpLabs/KnpGaufretteBundle#258]
I have such deprecation on PHP 8.1
`Deprecated: Return type of Knp\Bundle\GaufretteBundle\FilesystemMap::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /app/vendor/knplabs/knp-gaufrette-bundle/FilesystemMap.php on line 58`

**Comment by eXsio** [comment]
+1

**Comment by jukuan** [comment]
+1

**Comment by jukuan** [comment]
Here is my PR with correct fix:
https://github.com/KnpLabs/KnpGaufretteBundle/pull/259/files
