### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by tehpolicer** [KnpLabs/KnpGaufretteBundle#263]
Symfony 5.4 is generating deprecation warning with the following message:

Method "Symfony\Component\Console\Command\Command::execute()" might add "int" as a native return type declaration in the future. Do the same in child class "Knp\Bundle\GaufretteBundle\Command\FilesystemKeysCommand" now to avoid errors or add an explicit @return annotation to suppress this message.

This issue is easily resolvable by just adding return type of int to the command.

**Comment by Nek-** [comment]
I think we're good with this 🙌
