### ISSUE TITLE
Could not write the "XXXXXX.jpg" key content.

### ISSUE THREAD

**Issue by methodeprog** [KnpLabs/KnpGaufretteBundle#264]
Dear value member, your help will be great 
i use 
php >=7.2.5
Symfony 5.4.6
gaufrette ^0.7.2
aws/aws-sdk-php ^3.219
aws/aws-sdk-php-symfony ^2.4

This issue was related here
https://github.com/dustin10/VichUploaderBundle/issues/104

![FireShot Capture 1825 - Could not write the _Hongqi-S9-2021 jpg_ key content  (500 Internal _ - localhost](https://user-images.githubusercontent.com/18600282/163798209-bd780ac8-f273-43d1-be0e-5a8cc206b7ae.png)

**Comment by kevincerro** [comment]
Same issue here after adding ACL to AWS-S3 Adapter

`knp_gaufrette:
    stream_wrapper: ~

    adapters:
        ticket_images_adapter:
            aws_s3:
                service_id: 'Aws\S3\S3Client'
                bucket_name: '%env(AWS_BUCKET)%'
                detect_content_type: true
                options:
                    directory: 'ticket-images'
                    acl: 'public-read'`

**Comment by methodeprog** [comment]
work fine ! Thanks value member
