### ISSUE TITLE
Get Iterator not support PHP 8.1

### ISSUE THREAD

**Issue by konradmiszkurka** [KnpLabs/KnpGaufretteBundle#277]
Hello, i have symfony 4.4 and making right now doing php upgrade to 8.1 and have one issue with bundle.

Deprecated: Return type of Knp\Bundle\GaufretteBundle\FilesystemMap::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in */vendor/knplabs/knp-gaufrette-bundle/FilesystemMap.php on line 58

Versions:
knplabs/knp-gaufrette-bundle             v0.7.1

**Comment by timching** [comment]
Hi, got same warning
seems to fix that issue, can just upgrade to `v0.7.2`
or can try to patch this https://github.com/KnpLabs/KnpGaufretteBundle/pull/256 (https://github.com/KnpLabs/KnpGaufretteBundle/pull/256.patch)

ref.
https://github.com/KnpLabs/KnpGaufretteBundle/pull/259
https://github.com/KnpLabs/KnpGaufretteBundle/pull/256

**Comment by konradmiszkurka** [comment]
Ok Thanks
