### ISSUE TITLE
Retrive image url Amazon S3 -> Twig Template

### ISSUE THREAD

**Issue by andyepx** [KnpLabs/KnpGaufretteBundle#29]
Hello,

I have successfully set up VichUploaderBundle to work with GaufretteBundle and linked it to my Amazon S3 Bucket. Now, since the upload works fine I find my file in the S3 bucket with no problem but I cannot figure out how to retrive it from there.

I have the gaufrette wrapper to my file, which looks like gaufrette://amazon_s3_storage/test.jpg and I would like to see the picture in my Twig template. Is there any function I can use directly in my twig template?

From the controller point of view, the image seems to exist since file_exists($image->getImage()) returns 1 as result and $image->getImage() is the gaufrette wrapper mentioned above.

Thank you for your support!
Andy.

**Comment by nicolasmure** [comment]
Hello,

Sorry for the late answer. You can use [`gaufrette/extras`](https://github.com/Gaufrette/extras) to get an URL of your stored object.

**Comment by USvER** [comment]
Almost 5 years Carl!!! :D
