### ISSUE TITLE
Dropbox Adapter

### ISSUE THREAD

**Issue by sebakerckhof** [KnpLabs/KnpGaufretteBundle#36]
Hello,

Gaufrette seems to have a dropbox adapter, however, this is not present in the bundle configuration options. Can this be added?

**Comment by sela** [comment]
It looks there is Dropbox adapter but looking at it, it seems quite old as it implements the OAuth 1 so can't use the Access token generated by the App as there is only OAuth 2 now.

**Comment by NiR-** [comment]
Dropbox adapter will be deprecate soon.

**Comment by rubenrubiob** [comment]
@NiR- May I ask if you will integrate Dropbox with OAuth 2 or you will completely drop its support?

I am starting a project and I thought about using Dropbox, but if you will drop its support I will choose another cloud storage system.

Thank you.
