### ISSUE TITLE
Use the native filesystem map

### ISSUE THREAD

**Issue by IgorTimoshenko** [KnpLabs/KnpGaufretteBundle#39]
Hello!

I need to create some filesystem on-the-fly that is why needed the ability to append the filesystem to existing filesystem map. I do not understand why is used "Knp\Bundle\GaufretteBundle\FilesystemMap" and not "Gaufrette\FilesystemMap". The last enables work with filesystem map more flexibly.

Does it make a sense to refuse from "Knp\Bundle\GaufretteBundle\FilesystemMap" and use "Gaufrette\FilesystemMap"? I can make PR.

Thanks!

**Comment by lashus** [comment]
After 4 years I'm upvoting this - it should either extend the existing FilesystemMap and provide IteratorAggregate for it or simply use native Gaufrette FilesystemMap.

**Comment by nicolasmure** [comment]
@lashus yes I agree, PRs are welcome !
However, you can still override the [`knp_gaufrette.filesystem_map.class`](https://github.com/KnpLabs/KnpGaufretteBundle/blob/master/Resources/config/gaufrette.xml#L8) parameter to use a custom FilesystemMap class.

**Comment by lashus** [comment]
@nicolasmure  you're right - I haven't noticed it was injected :) So - should we remove it or leave it?

**Comment by nicolasmure** [comment]
Well, I'm gonna close this issue, but feel free to submit a pull request :)
