### ISSUE TITLE
PhpseclibSftp Adapter + solution for the fact that it eagerly loads/connects

### ISSUE THREAD

**Issue by calumbrodie** [KnpLabs/KnpGaufretteBundle#54]
This issue arises from using the recently added PhpseclibSftp adapter.

Rather than simply creating a new Adapter Factory - or using the existing sftp adapter factory - I've found a need to create a new adapter which lazy loads the underlying PhpseclibSftp adapter.

Reasons I've had to do this:
- Using the existing SftpAdapterFactory relies on the passed adapter being an instance of Ssh/Sftp (which this clearly isn't).
- Even if the above were solved - constructing the Net_SFTP object that this adapter uses tries to perform a connection _even if the adapter isn't being used in the request_ (It connects by virtue of being in the application configuration).

While the second issue here is more with the underlying adapter (than the simple configuration that this bundle provides) - I felt it better to commit everything into the same place rather than split the commit across two bundles. If the lazy loading implementation here is acceptable then it might better belong in the Gaufrette bundle itself.

I know the creation of the Adapter folder in the DependencyInjection folder isn't ideal - so perhaps it should be moved as described above

The commit in question is here:

https://github.com/calumbrodie/KnpGaufretteBundle/commit/0074d7031b5621cca938cf16f73b5d2bacd5af79

**Comment by rodrigm** [comment]
Related to https://github.com/KnpLabs/Gaufrette/issues/405

**Comment by NiR-** [comment]
Symfony has now a dedicated mechanism to lazy load services, so I believe this is now out of the scope of Gaufrette.

**Comment by florianajir** [comment]
> Symfony has now a dedicated mechanism to lazy load services

The symfony dedicated mechanisme to lazy load service don't work if we have to call login function on initialization like explained in doc https://github.com/KnpLabs/KnpGaufretteBundle/blob/master/Resources/docs/adapters/phpseclib_sftp.md
