### ISSUE TITLE
Issue to save files with local adapter

### ISSUE THREAD

**Issue by saharabear** [KnpLabs/KnpGaufretteBundle#55]
I am using a local file system adapter, all files are stored in one folder.

Is there a way to make Gaufrette store files in sub folders?

Thanks.

**Comment by nicolasmure** [comment]
Let's say that you have a local filesystem named `local` with `web/uploads` as the root dir.
You can access to it in a controller : 

```php
$fs = $this->get('gaufrette.local_filesystem');
$fs->write('dir/file.txt', 'content');
```
The `file.txt` file will be created in the `web/uploads/dir` directory.
