### ISSUE TITLE
OpenCloud Lazy Connection?

### ISSUE THREAD

**Issue by Richtermeister** [KnpLabs/KnpGaufretteBundle#72]
Hi all, 

Gaufrette has recently added lazy-loading OpenCloud connections (https://github.com/KnpLabs/Gaufrette/commit/5084853f18fab2ed27e5237ec9a9a105855f07ba). Is this feature currently supported in this bundle? I can't seem to find this in the documentation.. If not, I may be able to contribute this (assuming I can model it off the lazyloading Rackspace connection that already exists here).

Thanks!

**Comment by Rvanlaak** [comment]
Any news on using the lazy connection?

**Comment by Richtermeister** [comment]
Not on my end. I've actually resorted to just flagging filesystem services as lazyload in the Symfony container.

**Comment by ybert** [comment]
I have the same problem. 
Symfony initialialization takes 800ms even if I dont use the filesystem in my controller.

Did you fix it?

**Comment by Richtermeister** [comment]
@ybert No, this issue is not fixed, but the workaround is simple. Just flag the filesystem service as lazy.

**Comment by ybert** [comment]
I think it's easy but I have no idea where I put this flag?

Can you show me where to put this flag in the config?

Thank you for your time.

**Comment by ybert** [comment]
Ok I found the trick.
For me it was here:
<pre>
services:
    opencloud.connection:
        class: OpenCloud\OpenStack
        arguments:
          - %openstack_identity_url%
          - {username: %openstack_username%, password: %openstack_password%, tenantId: %openstack_tenant_id%}
    opencloud.object_store:
        lazy: true
        class: OpenCloud\ObjectStore\Service
        factory: ["@opencloud.connection", objectStoreService]
        arguments:
          - %openstack_object_storage_type%
          - %openstack_object_storage_region%
          - %openstack_object_storage_url%
</pre>

**Comment by NiR-** [comment]
As already noted, the best is to define opencloud objects as lazy-loaded services so they won't initialize any external connection every time the container is used. We'll remove LazyOpenCloud from the next major release and it is already deprecated for current minor version (see [here](https://github.com/KnpLabs/Gaufrette/issues/464) and [here](https://github.com/KnpLabs/Gaufrette/issues/466)). As such it'll not be implemented in the bundle.

For concerns about using OpenCloud adapter with OVH, there's already [an issue](https://github.com/KnpLabs/KnpGaufretteBundle/issues/142). But I don't if it works currently.
